FROM ubuntu:bionic
RUN apt update
RUN apt install -y wget
RUN wget https://github.com/daid/EmptyEpsilon/releases/download/EE-2020.02.18/Native_EmptyEpsilon_EE-2020.02.18.deb
RUN apt install -y libglu1-mesa novnc xserver-xorg net-tools
RUN apt install -y ./Native_EmptyEpsilon_EE-2020.02.18.deb
RUN wget https://sourceforge.net/projects/virtualgl/files/2.6.3/virtualgl_2.6.3_amd64.deb/download -O /tmp/virtualgl_2.6.3_amd64.deb
RUN apt install -y /tmp/virtualgl_2.6.3_amd64.deb
RUN wget https://sourceforge.net/projects/turbovnc/files/2.2.4/turbovnc_2.2.4_amd64.deb/download -O /tmp/turbovnc_2.2.4_amd64.deb
RUN apt install /tmp/turbovnc_2.2.4_amd64.deb
RUN /opt/VirtualGL/bin/vglserver_config -config +s +f +t
RUN mkdir -p /root/.vnc
RUN echo abcdefg | /opt/TurboVNC/bin/vncpasswd -f > /root/.vnc/passwd
RUN chmod 0600 /root/.vnc/passwd
RUN openssl req -x509 -newkey rsa:4096 -keyout /key.pem -out /cert.pem -days 365 -subj '/CN=localhost' -nodes
COPY run.sh run.sh
CMD ./run.sh
